# Generated by Django 2.2.6 on 2020-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temprature',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
