# Generated by Django 3.0.5 on 2020-04-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200427_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('emailId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
