# Generated by Django 3.0.5 on 2020-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timage', models.ImageField(upload_to='gallery/')),
                ('Reference', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
