# Generated by Django 3.0.5 on 2020-05-07 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
