# Generated by Django 3.0.5 on 2020-05-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_tutorial_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000)),
                ('BlogImg', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
